FROM oven/bun:latest

WORKDIR /usr/app/src

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

RUN bun install

RUN bun run db:generate

EXPOSE 8080

CMD ["sh", "-c", "bun run db:migrate:deploy && bun run start:backend"]



